export enum TipoCalle {
    AVENIDA = 'AVENIDA',
    CALLE = 'CALLE',
    CARRERA = 'CARRERA',
    AVENIDA_CARRERA = 'AVENIDA CARRERA',
    AVENIDA_CALLE = 'AVENIDA CALLE',
    DIAGONAL = 'DIAGONAL',
    TRANSVERSAL = 'TRANSVERSAL'
}